/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_8 (
    input clk,
    input rst,
    input [23:0] io_dip,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] result,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] s;
  
  reg [15:0] xb;
  
  always @* begin
    if (io_dip[16+0+0-:1] != 1'h1) begin
      s = a + b;
    end else begin
      s = a - b;
    end
    result = s;
    z = 1'h1;
    if (s == 1'h0) begin
      z = 1'h0;
    end
    n = s[15+0-:1];
    if (io_dip[16+0+0-:1] != 1'h1) begin
      v = ((a[15+0-:1] & b[15+0-:1] & ~s[15+0-:1]) | (~a[15+0-:1] & ~b[15+0-:1] & s[15+0-:1]));
    end else begin
      xb = ~b + 1'h1;
      v = ((a[15+0-:1] & xb[15+0-:1] & ~s[15+0-:1]) | (~a[15+0-:1] & ~xb[15+0-:1] & s[15+0-:1]));
    end
  end
endmodule
